# You've seen properties as things link hibernate.connection.url
# server.port=
# server.servlet.context-path=
server:
  port: 9005
  servlet:
    context-path: /
# in a properties file, it would look like spring.application.name
spring:
  application:
    name: aroma-project

#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://;serverName=ay-sebirka-server.database.windows.net;databaseName=ASebirka;encrypt=true
#    #below is the admin name
#    username: Sebirka
#    password: Ay2043#A
  datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://;serverName=akm-revprojectbd.database.windows.net;databaseName=AmAyDB;encrypt=true
      username: amrevpro
      password: Bokrrevature22

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

# Default actuator gives us the health endpoint, we will add a few others
management:
  endpoints:
    web:
      exposure:
        includes:
          - "beans"
          - "health"
          - "info"
